### ISSUE TITLE
NullPointerExeception in some cases when used with Turtl

### ISSUE THREAD

**Issue by chromicant** [lyonbros/cordova-plugin-secure-cache#1]
Basically, if you call up the recent apps, and swipe closed Turtl, you get two Null Pointer exceptions, which are at line 35 in SecureCacheService. Issue is summarized here: 

https://stackoverflow.com/questions/3963135/onstartcommand-after-service-process-is-killed-when-started-with-start-sticky.

In short, a START_STICKY service, if killed and restarted, will have it's intent set to null. Now, why it's happening and what's the best prevention, not quite sure.

**Comment by orthecreedence** [comment]
Great, thanks for the report! I'll push a fix to this before the next Turtl release.

**Comment by orthecreedence** [comment]
Fixed.
